mysql:
  enabled: true
  image: mysql:8.0
  rootPassword: wandb
  database: wandb_local
  username: wandb
  password: wandb
  service:
    name: mysql
    port: 3306
  secret:
    name: external-mysql-connection
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

redis:
  enabled: true
  image: redis:7
  password: ""
  service:
    name: redis
    port: 6379
  secret:
    name: external-redis-connection
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

minio:
  enabled: true
  image: quay.io/minio/minio:latest
  mcImage: quay.io/minio/mc:latest
  rootUser: minio
  rootPassword: minio123
  bucket: wandb
  region: us-east-1
  service:
    name: minio
    apiPort: 9000
    consolePort: 9090
  secret:
    name: external-objectstore-connection
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
