---
# MySQL - Percona XtraDB Cluster
# Scrapes mysqld-exporter sidecar from PXC nodes
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: mysql-pxc
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: pxc
  podMetricsEndpoints:
    - port: "9104"
      path: /metrics
---
# MySQL - ProxySQL
# Scrapes ProxySQL built-in Prometheus metrics
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: mysql-proxysql
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: proxysql
  podMetricsEndpoints:
    - port: "6070"
      path: /metrics
---
# Kafka - Strimzi
# Scrapes Kafka broker metrics via Strimzi Metrics Reporter
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: kafka-brokers
  namespace: default
spec:
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
  podMetricsEndpoints:
    - port: "9404"
      path: /metrics
---
# MinIO Tenant
# Scrapes MinIO metrics endpoint (auth disabled when telemetry enabled)
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: minio-tenant
  namespace: default
spec:
  selector:
    matchLabels:
      v1.min.io/tenant: wandb-minio
  podMetricsEndpoints:
    - port: "9000"
      path: /minio/metrics/v3
      scheme: http
---
# Redis
# Scrapes Redis exporter sidecar metrics
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: redis
  namespace: default
spec:
  selector:
    matchLabels:
      redis.redis.opstreelabs.in/kind: RedisReplication
  podMetricsEndpoints:
    - port: "9121"
      path: /metrics
---
# ClickHouse
# TODO: Implement clickhouse-exporter sidecar
# The Altinity ClickHouse operator doesn't support adding sidecar containers
# through the pod template. Requires alternative approach (mutating webhook, etc.)
# apiVersion: operator.victoriametrics.com/v1beta1
# kind: VMPodScrape
# metadata:
#   name: clickhouse
#   namespace: default
# spec:
#   selector:
#     matchLabels:
#       clickhouse.altinity.com/chi: wandb-ch-install
#   podMetricsEndpoints:
#     - port: "9363"
#       path: /metrics
