---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: wandb-operator
  namespace: default
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  namespaceSelector:
    matchNames:
      - operator-system
  endpoints:
    - port: https
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: clickhouse-operator
  namespace: default
spec:
  selector:
    matchLabels:
      app: clickhouse-operator
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: grafana-operator
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-operator
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victoria-metrics-operator
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics-operator
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
