version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    reviewers:
      - wandb/delivery-tooling-team

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    reviewers:
      - wandb/delivery-tooling-team

  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: daily
    reviewers:
      - wandb/delivery-tooling-team
