apiVersion: apps.wandb.com/v1
kind: WeightsAndBiases
metadata:
  labels:
    app.kubernetes.io/name: weightsandbiases
    app.kubernetes.io/instance: wandb
    wandb.ai/console-default: "true"
  name: wandb
spec:
  release:
    image: wandb/cdk8s:1.1.1
  config: {}
