apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  name: wandb
spec:
  mysql:
    managedMysql: null
    externalMysql:
      # required
      host:
        name: external-moco-connection
        key: Host
      port:
        name: external-moco-connection
        key: Port
      database:
        name: external-moco-connection
        key: Database
      username:
        name: external-moco-connection
        key: Username
      password:
        name: external-moco-connection
        key: Password
      URL:
        name: external-moco-connection
        key: url
      # optional
      # tls:
      #   name: external-moco-connection
      #   key: Tls
      # sslCa:
      #   name: external-moco-connection
      #   key: SslCa
      # sslCert:
      #   name: external-moco-connection
      #   key: SslCert
      # sslKey:
      #   name: external-moco-connection
      #   key: SslKey
