---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - namespaces/status
  - nodes
  - nodes/metrics
  - nodes/proxy
  - nodes/spec
  - nodes/stats
  - pods
  - pods/log
  - pods/status
  - replicationcontrollers
  - replicationcontrollers/status
  - resourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  - deployments/status
  - replicasets/status
  - statefulsets/status
  verbs:
  - get
- apiGroups:
  - apps.wandb.com
  resources:
  - applications
  - weightsandbiases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.wandb.com
  resources:
  - applications/finalizers
  - weightsandbiases/finalizers
  verbs:
  - update
- apiGroups:
  - apps.wandb.com
  resources:
  - applications/status
  - weightsandbiases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clickhouse.altinity.com
  resources:
  - clickhouseinstallations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clickhouse.altinity.com
  resources:
  - clickhouseinstallations/status
  verbs:
  - get
- apiGroups:
  - cloud.google.com
  resources:
  - backendconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - ingresses
  - ingresses/status
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - backendtlspolicies
  - gateways
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - backendtlspolicies/status
  - gateways/status
  - httproutes/status
  verbs:
  - get
- apiGroups:
  - gateway.nginx.org
  resources:
  - clientsettingspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.strimzi.io
  resources:
  - kafkanodepools
  - kafkas
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.strimzi.io
  resources:
  - kafkanodepools/status
  - kafkas/status
  - kafkatopics/status
  verbs:
  - get
  - update
- apiGroups:
  - moco.cybozu.com
  resources:
  - mysqlclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - moco.cybozu.com
  resources:
  - mysqlclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.gke.io
  resources:
  - healthcheckpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redis
  - redisreplications
  - redissentinels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redis/status
  verbs:
  - get
- apiGroups:
  - seaweed.seaweedfs.com
  resources:
  - seaweeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - seaweed.seaweedfs.com
  resources:
  - seaweeds/status
  verbs:
  - get
