# This rule is not used by the project operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over TriageRun resources.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: triagerun-admin-role
rules:
- apiGroups:
  - apps.wandb.com
  resources:
  - triageruns
  verbs:
  - '*'
- apiGroups:
  - apps.wandb.com
  resources:
  - triageruns/status
  verbs:
  - get
