resources:
  - ../crd/bases

patches:
  - path: patches/webhook_in_weightsandbiases.yaml
  - patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: "{{ .Release.Namespace }}/{{ .Release.Name }}-serving-cert"
      - op: add
        path: /metadata/annotations/helm.sh~1resource-policy
        value: "keep"
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
