apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: weightsandbiases.apps.wandb.com
spec:
  versions:
  - name: v1
    served: false
    storage: false
  - name: v2
    served: true
    storage: true