apiVersion: wandb.ai/v2
kind: WeightsAndBiases
metadata:
  name: weightsandbiases-sample
  namespace: wandb-system
spec:
  profile: dev
  infra:
    streaming:
      enabled: true
      type: kafka
      configMapRef:
        name: kafka-operator-templates
        namespace: wandb-system