{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minio.service.name }}
  labels:
    {{- include "test-infra.componentLabels" (dict "root" . "component" "minio") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: minio
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: 9000
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: 9090
{{- end }}
