{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.secret.name }}
  labels:
    {{- include "test-infra.componentLabels" (dict "root" . "component" "minio") | nindent 4 }}
type: Opaque
stringData:
  Host: {{ include "test-infra.minioHost" . | quote }}
  Port: {{ .Values.minio.service.apiPort | quote }}
  Bucket: {{ .Values.minio.bucket | quote }}
  Region: {{ .Values.minio.region | quote }}
  AccessKey: {{ .Values.minio.rootUser | quote }}
  SecretKey: {{ .Values.minio.rootPassword | quote }}
{{- end }}
