{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
    {{- include "test-infra.componentLabels" (dict "root" . "component" "mysql") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: mysql
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: 3306
{{- end }}
