{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secret.name }}
  labels:
    {{- include "test-infra.componentLabels" (dict "root" . "component" "mysql") | nindent 4 }}
type: Opaque
stringData:
  Host: {{ include "test-infra.mysqlHost" . | quote }}
  Port: {{ .Values.mysql.service.port | quote }}
  Database: {{ .Values.mysql.database | quote }}
  Username: {{ .Values.mysql.username | quote }}
  Password: {{ .Values.mysql.password | quote }}
{{- end }}
