{{- if .Values.seaweedfs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.seaweedfs.secret.name }}
  labels:
    {{- include "test-infra.componentLabels" (dict "root" . "component" "seaweedfs") | nindent 4 }}
type: Opaque
stringData:
  Provider: {{ .Values.seaweedfs.provider | quote }}
  Host: {{ include "test-infra.seaweedfsHost" . | quote }}
  Port: {{ .Values.seaweedfs.service.apiPort | quote }}
  Bucket: {{ .Values.seaweedfs.bucket | quote }}
  Region: {{ .Values.seaweedfs.region | quote }}
  AccessKey: {{ .Values.seaweedfs.accessKey | quote }}
  SecretKey: {{ .Values.seaweedfs.secretKey | quote }}
{{- end }}
