apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  name: wandb
spec:
  objectStore:
    managedObjectStore: null
    externalObjectStore:
      # provider: secret key holding s3 (default), gcs, or azure; omit to default to s3.
      provider:
        name: external-objectstore-connection
        key: Provider
      # required
      endpoint:
        name: external-objectstore-connection
        key: Host
      port:
        name: external-objectstore-connection
        key: Port
      bucket:
        name: external-objectstore-connection
        key: Bucket
      region:
        name: external-objectstore-connection
        key: Region
      URL:
        name: external-objectstore-connection
        key: url
      accessKey:
        name: external-objectstore-connection
        key: AccessKey
      secretKey:
        name: external-objectstore-connection
        key: SecretKey
