apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  name: wandb
spec:
  objectStore:
    managedObjectStore: null
    externalObjectStore:
      # required
      endpoint:
        name: external-objectstore-connection
        key: Host
      bucket:
        name: external-objectstore-connection
        key: Bucket
      region:
        name: external-objectstore-connection
        key: Region
      URL:
        name: external-objectstore-connection
        key: url
      # optional
      # accessKey:
      #   name: external-objectstore-connection
      #   key: AccessKey
      # secretKey:
      #   name: external-objectstore-connection
      #   key: SecretKey
