package seaweedfs

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("S3IdentityConfig", func() {
	Describe("Round-trip parsing", func() {
		DescribeTable("should correctly parse config generated by toJSON",
			func(accessKey, secretKey string) {
				original := buildS3IdentityConfig(accessKey, secretKey)
				jsonStr, err := original.toJSON()
				Expect(err).ToNot(HaveOccurred())

				parsed, err := parseS3IdentityConfig(jsonStr)
				Expect(err).ToNot(HaveOccurred())

				Expect(parsed.Identities).To(HaveLen(1))
				Expect(parsed.Identities[0].Credentials).To(HaveLen(1))
				Expect(parsed.Identities[0].Credentials[0].AccessKey).To(Equal(accessKey))
				Expect(parsed.Identities[0].Credentials[0].SecretKey).To(Equal(secretKey))
			},
			Entry("basic credentials", "admin", "password123"),
			Entry("with special characters", "user", "p@ssw0rd!#$"),
			Entry("long credentials", "very-long-username", "very-long-password-with-many-characters"),
			Entry("minimum values", "a", "b"),
		)

		It("should extract secret key from config", func() {
			config := buildS3IdentityConfig("admin", "mysecret")
			key, err := extractSecretKey(config, "admin")
			Expect(err).ToNot(HaveOccurred())
			Expect(key).To(Equal("mysecret"))
		})

		It("should return error for empty config", func() {
			config := s3IdentityConfig{}
			_, err := extractSecretKey(config, "admin")
			Expect(err).To(HaveOccurred())
		})

		It("should handle malformed JSON", func() {
			_, err := parseS3IdentityConfig("not json")
			Expect(err).To(HaveOccurred())
		})

		Context("idempotency", func() {
			It("should be idempotent - parse(toJSON(parse(toJSON(x)))) == parse(toJSON(x))", func() {
				original := buildS3IdentityConfig("admin", "password123")

				firstJSON, err := original.toJSON()
				Expect(err).ToNot(HaveOccurred())
				firstParsed, err := parseS3IdentityConfig(firstJSON)
				Expect(err).ToNot(HaveOccurred())

				secondJSON, err := firstParsed.toJSON()
				Expect(err).ToNot(HaveOccurred())

				Expect(secondJSON).To(Equal(firstJSON))
			})
		})
	})
})
