---
apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  labels:
    app.kubernetes.io/name: weightsandbiases
    app.kubernetes.io/instance: weightsandbiases-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: wandb-default-v2
spec:
  profile: dev
  streaming:
    enabled: true
    type: kafka
