apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  name: wandb-dev-v2
spec:
  wandb:
    hostname: http://localhost:8080
  size: dev
  mysql:
    enabled: true
  redis:
    enabled: true
  kafka:
    enabled: true
  minio:
    enabled: true
  clickhouse:
    enabled: true
