apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  name: wandb-small-v2
  namespace: default
spec:
  profile: small
  database:
    enabled: true
    type: percona
    storageSize: 5Gi
    backup:
      enabled: true
      storageName: default-backup
      storageType: filesystem
      filesystem:
        storageSize: 5Gi
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
      timeoutSeconds: 600
  redis:
    enabled: true
    storageSize: 1Gi
  kafka:
    enabled: true
    storageSize: 10Gi
    replicas: 3
    backup:
      enabled: true
      storageName: default-backup
      storageType: filesystem
      filesystem:
        storageSize: 5Gi
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
      timeoutSeconds: 600
  objStorage:
    enabled: true
    storageSize: 10Gi
    replicas: 3
    backup:
      enabled: true
      storageName: default-backup
      storageType: filesystem
      filesystem:
        storageSize: 5Gi
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
      timeoutSeconds: 600
  clickhouse:
    enabled: true
    storageSize: 10Gi
    replicas: 3
    backup:
      enabled: true
      storageName: default-backup
      storageType: filesystem
      filesystem:
        storageSize: 5Gi
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
      timeoutSeconds: 600
