apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  name: wandb-small-v2
spec:
  enableOIDCDiscovery: true
  size: small
  wandb:
    hostname: http://localhost
    features:
      proxy: true
  retentionPolicy:
    onDelete: preserve
  mysql:
    enabled: true
    telemetry:
      enabled: true
  redis:
    enabled: true
    telemetry:
      enabled: true
  kafka:
    enabled: true
    telemetry:
      enabled: true
  minio:
    enabled: true
    telemetry:
      enabled: true
  clickhouse:
    enabled: true
    telemetry:
      enabled: true
