apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  name: wandb-dev-v2
  namespace: default
spec:
  profile: dev
  database:
    enabled: true
    type: percona
    storageSize: 5Gi
    backup:
      enabled: true
      storageName: default-backup
      storageType: filesystem
      filesystem:
        storageSize: 6Gi
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
      timeoutSeconds: 600