apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  name: wandb-dev-v2
  namespace: default
spec:
  profile: dev
  database:
    enabled: true
    type: percona
    storageSize: 5Gi
    backup:
      enabled: false
  redis:
    enabled: true
    storageSize: 1Gi
  kafka:
    enabled: true
    storageSize: 10Gi
    replicas: 1
    backup:
      enabled: false
  objStorage:
    enabled: true
    storageSize: 10Gi
    replicas: 1
    backup:
      enabled: false
