apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  name: wandb-small-v2
spec:
  size: small
  mysql:
    enabled: true
  redis:
    enabled: true
  kafka:
    enabled: true
  minio:
    enabled: true
  clickhouse:
    enabled: true
