apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weights-and-biases
  namespace: default
  labels:
    app.kubernetes.io/part-of: wandb
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - delete
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/log
      - configmaps
      - services
      - serviceaccounts
      - events
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weights-and-biases
  namespace: default
  labels:
    app.kubernetes.io/part-of: wandb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: weights-and-biases
subjects:
  - kind: ServiceAccount
    name: weights-and-biases
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: weights-and-biases-service-account-issuer-discovery
  labels:
    app.kubernetes.io/part-of: wandb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:service-account-issuer-discovery
subjects:
  - kind: Group
    name: system:unauthenticated
    apiGroup: rbac.authorization.k8s.io
