apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  name: wandb
spec:
  wandb:
    hostname: http://localhost
    internalServiceAuth:
      enabled: true
    features:
      proxy: true
    manifestRepository: "file:///server-manifest"
    version: "0.79.0"
  size: dev
  retentionPolicy:
    onDelete: detach
  mysql:
    managedMysql:
      deploymentType: "mysql"
      telemetry:
        enabled: true
  redis:
    enabled: true
    telemetry:
      enabled: true
  kafka:
    enabled: true
    telemetry:
      enabled: true
  minio:
    enabled: true
    telemetry:
      enabled: true
  clickhouse:
    enabled: true
    telemetry:
      enabled: true
