apiVersion: v2
name: operator
description: A Helm chart for Weights & Biases operator
type: application
version: 2.0.0-alpha.1
appVersion: "2.0.0-alpha.1"
maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com

dependencies:
  - name: wandb-base
    version: 0.11.8
    alias: wandb-operator
    repository: https://charts.wandb.ai/
    condition: wandb-operator.enabled
  - name: mysql-operator
    version: 2.1.11
    repository: https://mysql.github.io/mysql-operator/
    condition: mysql-operator.enabled
  - name: redis-operator
    version: 0.22.2
    repository: https://ot-container-kit.github.io/helm-charts
    condition: redis-operator.enabled
  - name: strimzi-kafka-operator
    version: 0.50.0
    repository: https://strimzi.io/charts
    condition: strimzi-kafka-operator.enabled
  - name: seaweedfs-operator
    version: 0.1.13
    repository: https://seaweedfs.github.io/seaweedfs-operator/
    condition: seaweedfs-operator.enabled
  - name: altinity-clickhouse-operator
    version: 0.26.3
    repository: https://helm.altinity.com
    condition: altinity-clickhouse-operator.enabled
  - name: victoria-metrics-operator
    version: 0.58.1
    repository: https://victoriametrics.github.io/helm-charts/
    condition: victoria-metrics-operator.enabled
  - name: grafana-operator
    version: 5.21.4
    repository: https://grafana.github.io/helm-charts
    condition: grafana-operator.enabled
  - name: telemetry
    version: 0.1.0
    repository: file://../telemetry
