- op: replace
  path: /spec/template/spec/securityContext
  value:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
- op: replace
  path: /spec/template/spec/containers/0/securityContext
  value:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: KAFKA_FSGROUP
    value: "0"
