package tenant

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("MinioConfigFile", func() {
	Describe("Round-trip parsing", func() {
		DescribeTable("should correctly parse config generated by toFileContents",
			func(rootUser, rootPassword, browserSetting string) {
				original := buildMinioConfigFile(rootUser, rootPassword, browserSetting)
				fileContents := original.toFileContents()
				parsed := parseMinioConfigFile(fileContents)

				Expect(parsed.rootUser).To(Equal(original.rootUser))
				Expect(parsed.rootPassword).To(Equal(original.rootPassword))
				Expect(parsed.minioBrowserSetting).To(Equal(original.minioBrowserSetting))
			},
			Entry("basic credentials", "admin", "password123", "on"),
			Entry("with special characters in password", "user", "p@ssw0rd!#$", "off"),
			Entry("empty browser setting", "root", "secret", ""),
			Entry("long credentials", "very-long-username", "very-long-password-with-many-characters", "on"),
			Entry("with spaces", "user name", "pass word", "on"),
			Entry("with quotes-like characters", "user", "can't-have-quotes", "on"),
			Entry("minimum values", "a", "b", "c"),
			Entry("browser setting variations", "admin", "password", "redirect"),
		)

		DescribeTable("should handle edge cases",
			func(rootUser, rootPassword, browserSetting string) {
				original := buildMinioConfigFile(rootUser, rootPassword, browserSetting)
				fileContents := original.toFileContents()
				parsed := parseMinioConfigFile(fileContents)
				reparsed := parsed.toFileContents()

				Expect(reparsed).To(Equal(fileContents))
			},
			Entry("empty strings", "", "", ""),
			Entry("only root user", "admin", "", ""),
			Entry("only root password", "", "password", ""),
			Entry("only browser setting", "", "", "on"),
			Entry("typical production config", "minio", "minio123", "on"),
			Entry("secure password", "admin", "Sup3rS3cr3tP@ssw0rd!", "off"),
		)

		Context("parsing malformed input", func() {
			It("should return empty config for completely invalid input", func() {
				parsed := parseMinioConfigFile("invalid input")
				Expect(parsed.rootUser).To(Equal(""))
				Expect(parsed.rootPassword).To(Equal(""))
				Expect(parsed.minioBrowserSetting).To(Equal(""))
			})

			It("should handle missing MINIO_ROOT_USER", func() {
				fileContents := `export MINIO_ROOT_PASSWORD="password"
export MINIO_BROWSER="on"`
				parsed := parseMinioConfigFile(fileContents)
				Expect(parsed.rootUser).To(Equal(""))
				Expect(parsed.rootPassword).To(Equal("password"))
				Expect(parsed.minioBrowserSetting).To(Equal("on"))
			})

			It("should handle missing MINIO_ROOT_PASSWORD", func() {
				fileContents := `export MINIO_ROOT_USER="admin"
export MINIO_BROWSER="on"`
				parsed := parseMinioConfigFile(fileContents)
				Expect(parsed.rootUser).To(Equal("admin"))
				Expect(parsed.rootPassword).To(Equal(""))
				Expect(parsed.minioBrowserSetting).To(Equal("on"))
			})

			It("should handle missing MINIO_BROWSER", func() {
				fileContents := `export MINIO_ROOT_USER="admin"
export MINIO_ROOT_PASSWORD="password"`
				parsed := parseMinioConfigFile(fileContents)
				Expect(parsed.rootUser).To(Equal("admin"))
				Expect(parsed.rootPassword).To(Equal("password"))
				Expect(parsed.minioBrowserSetting).To(Equal(""))
			})

			It("should handle extra whitespace", func() {
				fileContents := `export MINIO_ROOT_USER="admin"
export MINIO_ROOT_PASSWORD="password"
export MINIO_BROWSER="on"`
				parsed := parseMinioConfigFile(fileContents)
				Expect(parsed.rootUser).To(Equal("admin"))
				Expect(parsed.rootPassword).To(Equal("password"))
				Expect(parsed.minioBrowserSetting).To(Equal("on"))
			})

			It("should handle values with escaped characters", func() {
				config := buildMinioConfigFile("user", "pass\\nword", "on")
				fileContents := config.toFileContents()
				parsed := parseMinioConfigFile(fileContents)
				Expect(parsed.rootPassword).To(Equal("pass\\nword"))
			})
		})

		Context("idempotency", func() {
			It("should be idempotent - parse(toFileContents(parse(toFileContents(x)))) == parse(toFileContents(x))", func() {
				original := buildMinioConfigFile("admin", "password123", "on")

				firstRound := original.toFileContents()
				firstParsed := parseMinioConfigFile(firstRound)

				secondRound := firstParsed.toFileContents()
				secondParsed := parseMinioConfigFile(secondRound)

				Expect(secondParsed).To(Equal(firstParsed))
				Expect(secondRound).To(Equal(firstRound))
			})
		})
	})
})
