{{- if .Values.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.role.type }}
metadata:
  name: {{ include "watchtower.roleName" . }}
  {{- if eq .Values.role.type "Role" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "watchtower.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.role.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ ternary "RoleBinding" "ClusterRoleBinding" (eq .Values.role.type "Role") }}
metadata:
  name: {{ include "watchtower.roleName" . }}
  {{- if eq .Values.role.type "Role" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "watchtower.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "watchtower.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ .Values.role.type }}
  name: {{ include "watchtower.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
