/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v2

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BaseDeploymentSpec contains configuration shared by application deployments.
// Embed it anonymously with json:",inline" to preserve the existing spec paths.
type BaseDeploymentSpec struct {
	// Size is akin to high-level environment info
	// +kubebuilder:validation:Enum=dev;micro;small;medium;large;xlarge;xxlarge
	Size Size `json:"size,omitempty"`

	// RequireLimits By default, only resource requests are set for deployments, set to true to also set resource limits
	RequireLimits bool `json:"requireLimits,omitempty"`

	RetentionPolicy RetentionPolicy `json:"retentionPolicy"`

	// Global holds settings shared across all managed components.
	// +optional
	Global GlobalSpec `json:"global,omitempty"`

	Affinity    *corev1.Affinity     `json:"affinity,omitempty"`
	Tolerations *[]corev1.Toleration `json:"tolerations,omitempty"`

	// MySQL, Redis, ObjectStore and ClickHouse are keyed by instance name. The
	// reserved DefaultInstanceName key identifies the fallback instance used when
	// an application requests an instance that is not provisioned.
	MySQL       map[string]MySQLSpec       `json:"mysql,omitempty"`
	Redis       map[string]RedisSpec       `json:"redis,omitempty"`
	Kafka       KafkaSpec                  `json:"kafka,omitempty"`
	ObjectStore map[string]ObjectStoreSpec `json:"objectStore,omitempty"`
	ClickHouse  map[string]ClickHouseSpec  `json:"clickhouse,omitempty"`

	// Networking configures how the application is exposed externally.
	// +optional
	Networking NetworkingSpec `json:"networking,omitempty"`
}

// BaseWorkloadSpec contains the manifest and workload configuration shared by
// applications. WeightsAndBiases embeds it within spec.wandb so existing field
// paths remain unchanged.
type BaseWorkloadSpec struct {
	Hostname           string          `json:"hostname"`
	ManifestRepository string          `json:"manifestRepository,omitempty"`
	Version            string          `json:"version"`
	Features           map[string]bool `json:"features"`

	ServiceAccount ServiceAccountSpec `json:"serviceAccount,omitempty"`

	// Probes configures default health probes for application workload
	// containers generated by the operator. The full Kubernetes Probe shape is
	// exposed so operators can tune timings and handlers for their environment.
	// Explicit probes on generated containers remain authoritative; these values
	// only fill missing probes or missing probe fields.
	// +optional
	Probes WandbProbeDefaults `json:"probes,omitempty"`

	// +optional
	AdditionalHostnames []string `json:"additionalHostnames,omitempty"`

	// Applications overlays sizing-derived per-application config, keyed by
	// manifest application name. Unknown keys are logged and ignored.
	// +optional
	Applications map[string]WandbApplicationOverride `json:"applications,omitempty"`
}

// BaseDeploymentStatus contains the observed deployment and infrastructure state
// shared by applications. It is embedded inline in each application status.
type BaseDeploymentStatus struct {
	Ready bool `json:"ready"`

	// Conditions includes the standard Ready condition for the current generation.
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// MySQLStatus, RedisStatus, ObjectStoreStatus and ClickHouseStatus are keyed
	// by instance name, mirroring the corresponding spec maps.
	MySQLStatus       map[string]MysqlInfraStatus       `json:"mysqlStatus,omitempty"`
	RedisStatus       map[string]RedisInfraStatus       `json:"redisStatus,omitempty"`
	KafkaStatus       KafkaInfraStatus                  `json:"kafkaStatus,omitempty"`
	ObjectStoreStatus map[string]ObjectStoreInfraStatus `json:"objectStoreStatus,omitempty"`
	ClickHouseStatus  map[string]ClickHouseInfraStatus  `json:"clickhouseStatus,omitempty"`
	TelemetryStatus   TelemetryInfraStatus              `json:"telemetryStatus,omitempty"`

	// GeneratedSecrets stores references to secrets generated by the operator
	// from the server manifest's generatedSecrets section. The key is the
	// logical secret name from the manifest, and the value is a SecretKeySelector
	// referencing the concrete Secret and key that holds the generated value.
	GeneratedSecrets   map[string]corev1.SecretKeySelector `json:"generatedSecrets,omitempty"`
	ObservedGeneration int64                               `json:"observedGeneration"`

	// +optional
	GatewayStatus *GatewayStatusSummary `json:"gatewayStatus,omitempty"`
	// +optional
	IngressStatus *IngressStatusSummary `json:"ingressStatus,omitempty"`
}

// BaseWorkloadStatus contains the observed hostname and application workloads.
// WeightsAndBiases embeds it within status.wandb for wire compatibility.
type BaseWorkloadStatus struct {
	Hostname string `json:"hostname"`

	// +kubebuilder:default:={}
	Applications map[string]ApplicationStatus `json:"applications,omitempty"`
}
