//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Application) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationList) DeepCopyInto(out *ApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Application, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationList.
func (in *ApplicationList) DeepCopy() *ApplicationList {
	if in == nil {
		return nil
	}
	out := new(ApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSpec) DeepCopyInto(out *ApplicationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSpec.
func (in *ApplicationSpec) DeepCopy() *ApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatus) DeepCopyInto(out *ApplicationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatus.
func (in *ApplicationStatus) DeepCopy() *ApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBBackupFilesystemSpec) DeepCopyInto(out *WBBackupFilesystemSpec) {
	*out = *in
	out.StorageSize = in.StorageSize.DeepCopy()
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBBackupFilesystemSpec.
func (in *WBBackupFilesystemSpec) DeepCopy() *WBBackupFilesystemSpec {
	if in == nil {
		return nil
	}
	out := new(WBBackupFilesystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBBackupS3Spec) DeepCopyInto(out *WBBackupS3Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBBackupS3Spec.
func (in *WBBackupS3Spec) DeepCopy() *WBBackupS3Spec {
	if in == nil {
		return nil
	}
	out := new(WBBackupS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBBackupSpec) DeepCopyInto(out *WBBackupSpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(WBBackupS3Spec)
		**out = **in
	}
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(WBBackupFilesystemSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBBackupSpec.
func (in *WBBackupSpec) DeepCopy() *WBBackupSpec {
	if in == nil {
		return nil
	}
	out := new(WBBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBBackupStatus) DeepCopyInto(out *WBBackupStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBBackupStatus.
func (in *WBBackupStatus) DeepCopy() *WBBackupStatus {
	if in == nil {
		return nil
	}
	out := new(WBBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBClickHouseConfig) DeepCopyInto(out *WBClickHouseConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBClickHouseConfig.
func (in *WBClickHouseConfig) DeepCopy() *WBClickHouseConfig {
	if in == nil {
		return nil
	}
	out := new(WBClickHouseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBClickHouseConnection) DeepCopyInto(out *WBClickHouseConnection) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBClickHouseConnection.
func (in *WBClickHouseConnection) DeepCopy() *WBClickHouseConnection {
	if in == nil {
		return nil
	}
	out := new(WBClickHouseConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBClickHouseSpec) DeepCopyInto(out *WBClickHouseSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBClickHouseSpec.
func (in *WBClickHouseSpec) DeepCopy() *WBClickHouseSpec {
	if in == nil {
		return nil
	}
	out := new(WBClickHouseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBClickHouseStatus) DeepCopyInto(out *WBClickHouseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]WBStatusCondition, len(*in))
		copy(*out, *in)
	}
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
	in.Connection.DeepCopyInto(&out.Connection)
	in.BackupStatus.DeepCopyInto(&out.BackupStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBClickHouseStatus.
func (in *WBClickHouseStatus) DeepCopy() *WBClickHouseStatus {
	if in == nil {
		return nil
	}
	out := new(WBClickHouseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBKafkaBackupSpec) DeepCopyInto(out *WBKafkaBackupSpec) {
	*out = *in
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(WBBackupFilesystemSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBKafkaBackupSpec.
func (in *WBKafkaBackupSpec) DeepCopy() *WBKafkaBackupSpec {
	if in == nil {
		return nil
	}
	out := new(WBKafkaBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBKafkaConfig) DeepCopyInto(out *WBKafkaConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.ReplicationConfig = in.ReplicationConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBKafkaConfig.
func (in *WBKafkaConfig) DeepCopy() *WBKafkaConfig {
	if in == nil {
		return nil
	}
	out := new(WBKafkaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBKafkaConnection) DeepCopyInto(out *WBKafkaConnection) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBKafkaConnection.
func (in *WBKafkaConnection) DeepCopy() *WBKafkaConnection {
	if in == nil {
		return nil
	}
	out := new(WBKafkaConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBKafkaReplicationConfig) DeepCopyInto(out *WBKafkaReplicationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBKafkaReplicationConfig.
func (in *WBKafkaReplicationConfig) DeepCopy() *WBKafkaReplicationConfig {
	if in == nil {
		return nil
	}
	out := new(WBKafkaReplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBKafkaSpec) DeepCopyInto(out *WBKafkaSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.Backup.DeepCopyInto(&out.Backup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBKafkaSpec.
func (in *WBKafkaSpec) DeepCopy() *WBKafkaSpec {
	if in == nil {
		return nil
	}
	out := new(WBKafkaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBKafkaStatus) DeepCopyInto(out *WBKafkaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]WBStatusCondition, len(*in))
		copy(*out, *in)
	}
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
	in.Connection.DeepCopyInto(&out.Connection)
	in.BackupStatus.DeepCopyInto(&out.BackupStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBKafkaStatus.
func (in *WBKafkaStatus) DeepCopy() *WBKafkaStatus {
	if in == nil {
		return nil
	}
	out := new(WBKafkaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBMinioConfig) DeepCopyInto(out *WBMinioConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBMinioConfig.
func (in *WBMinioConfig) DeepCopy() *WBMinioConfig {
	if in == nil {
		return nil
	}
	out := new(WBMinioConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBMinioConnection) DeepCopyInto(out *WBMinioConnection) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBMinioConnection.
func (in *WBMinioConnection) DeepCopy() *WBMinioConnection {
	if in == nil {
		return nil
	}
	out := new(WBMinioConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBMinioSpec) DeepCopyInto(out *WBMinioSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBMinioSpec.
func (in *WBMinioSpec) DeepCopy() *WBMinioSpec {
	if in == nil {
		return nil
	}
	out := new(WBMinioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBMinioStatus) DeepCopyInto(out *WBMinioStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]WBStatusCondition, len(*in))
		copy(*out, *in)
	}
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
	in.Connection.DeepCopyInto(&out.Connection)
	in.BackupStatus.DeepCopyInto(&out.BackupStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBMinioStatus.
func (in *WBMinioStatus) DeepCopy() *WBMinioStatus {
	if in == nil {
		return nil
	}
	out := new(WBMinioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBMySQLConfig) DeepCopyInto(out *WBMySQLConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBMySQLConfig.
func (in *WBMySQLConfig) DeepCopy() *WBMySQLConfig {
	if in == nil {
		return nil
	}
	out := new(WBMySQLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBMySQLConnection) DeepCopyInto(out *WBMySQLConnection) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBMySQLConnection.
func (in *WBMySQLConnection) DeepCopy() *WBMySQLConnection {
	if in == nil {
		return nil
	}
	out := new(WBMySQLConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBMySQLSpec) DeepCopyInto(out *WBMySQLSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBMySQLSpec.
func (in *WBMySQLSpec) DeepCopy() *WBMySQLSpec {
	if in == nil {
		return nil
	}
	out := new(WBMySQLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBMySQLStatus) DeepCopyInto(out *WBMySQLStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]WBStatusCondition, len(*in))
		copy(*out, *in)
	}
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
	in.Connection.DeepCopyInto(&out.Connection)
	in.BackupStatus.DeepCopyInto(&out.BackupStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBMySQLStatus.
func (in *WBMySQLStatus) DeepCopy() *WBMySQLStatus {
	if in == nil {
		return nil
	}
	out := new(WBMySQLStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisConfig) DeepCopyInto(out *WBRedisConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisConfig.
func (in *WBRedisConfig) DeepCopy() *WBRedisConfig {
	if in == nil {
		return nil
	}
	out := new(WBRedisConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisConnection) DeepCopyInto(out *WBRedisConnection) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisConnection.
func (in *WBRedisConnection) DeepCopy() *WBRedisConnection {
	if in == nil {
		return nil
	}
	out := new(WBRedisConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisSentinelConfig) DeepCopyInto(out *WBRedisSentinelConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisSentinelConfig.
func (in *WBRedisSentinelConfig) DeepCopy() *WBRedisSentinelConfig {
	if in == nil {
		return nil
	}
	out := new(WBRedisSentinelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisSentinelSpec) DeepCopyInto(out *WBRedisSentinelSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisSentinelSpec.
func (in *WBRedisSentinelSpec) DeepCopy() *WBRedisSentinelSpec {
	if in == nil {
		return nil
	}
	out := new(WBRedisSentinelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisSpec) DeepCopyInto(out *WBRedisSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.Sentinel.DeepCopyInto(&out.Sentinel)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisSpec.
func (in *WBRedisSpec) DeepCopy() *WBRedisSpec {
	if in == nil {
		return nil
	}
	out := new(WBRedisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisStatus) DeepCopyInto(out *WBRedisStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]WBStatusCondition, len(*in))
		copy(*out, *in)
	}
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisStatus.
func (in *WBRedisStatus) DeepCopy() *WBRedisStatus {
	if in == nil {
		return nil
	}
	out := new(WBRedisStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBStatusCondition) DeepCopyInto(out *WBStatusCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBStatusCondition.
func (in *WBStatusCondition) DeepCopy() *WBStatusCondition {
	if in == nil {
		return nil
	}
	out := new(WBStatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiases) DeepCopyInto(out *WeightsAndBiases) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiases.
func (in *WeightsAndBiases) DeepCopy() *WeightsAndBiases {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiases)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WeightsAndBiases) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiasesList) DeepCopyInto(out *WeightsAndBiasesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WeightsAndBiases, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiasesList.
func (in *WeightsAndBiasesList) DeepCopy() *WeightsAndBiasesList {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiasesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WeightsAndBiasesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiasesSpec) DeepCopyInto(out *WeightsAndBiasesSpec) {
	*out = *in
	in.MySQL.DeepCopyInto(&out.MySQL)
	in.Redis.DeepCopyInto(&out.Redis)
	in.Kafka.DeepCopyInto(&out.Kafka)
	in.Minio.DeepCopyInto(&out.Minio)
	in.ClickHouse.DeepCopyInto(&out.ClickHouse)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiasesSpec.
func (in *WeightsAndBiasesSpec) DeepCopy() *WeightsAndBiasesSpec {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiasesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiasesStatus) DeepCopyInto(out *WeightsAndBiasesStatus) {
	*out = *in
	in.MySQLStatus.DeepCopyInto(&out.MySQLStatus)
	in.RedisStatus.DeepCopyInto(&out.RedisStatus)
	in.KafkaStatus.DeepCopyInto(&out.KafkaStatus)
	in.MinioStatus.DeepCopyInto(&out.MinioStatus)
	in.ClickHouseStatus.DeepCopyInto(&out.ClickHouseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiasesStatus.
func (in *WeightsAndBiasesStatus) DeepCopy() *WeightsAndBiasesStatus {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiasesStatus)
	in.DeepCopyInto(out)
	return out
}
