//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Application) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationList) DeepCopyInto(out *ApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Application, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationList.
func (in *ApplicationList) DeepCopy() *ApplicationList {
	if in == nil {
		return nil
	}
	out := new(ApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSpec) DeepCopyInto(out *ApplicationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSpec.
func (in *ApplicationSpec) DeepCopy() *ApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatus) DeepCopyInto(out *ApplicationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatus.
func (in *ApplicationStatus) DeepCopy() *ApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapReference) DeepCopyInto(out *ConfigMapReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapReference.
func (in *ConfigMapReference) DeepCopy() *ConfigMapReference {
	if in == nil {
		return nil
	}
	out := new(ConfigMapReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBComponentStatus) DeepCopyInto(out *WBComponentStatus) {
	*out = *in
	in.InfraStatus.DeepCopyInto(&out.InfraStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBComponentStatus.
func (in *WBComponentStatus) DeepCopy() *WBComponentStatus {
	if in == nil {
		return nil
	}
	out := new(WBComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBInfraSpec) DeepCopyInto(out *WBInfraSpec) {
	*out = *in
	in.Streaming.DeepCopyInto(&out.Streaming)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBInfraSpec.
func (in *WBInfraSpec) DeepCopy() *WBInfraSpec {
	if in == nil {
		return nil
	}
	out := new(WBInfraSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBInfraStatus) DeepCopyInto(out *WBInfraStatus) {
	*out = *in
	in.StreamingStatus.DeepCopyInto(&out.StreamingStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBInfraStatus.
func (in *WBInfraStatus) DeepCopy() *WBInfraStatus {
	if in == nil {
		return nil
	}
	out := new(WBInfraStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBStreamingSpec) DeepCopyInto(out *WBStreamingSpec) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBStreamingSpec.
func (in *WBStreamingSpec) DeepCopy() *WBStreamingSpec {
	if in == nil {
		return nil
	}
	out := new(WBStreamingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBStreamingStatus) DeepCopyInto(out *WBStreamingStatus) {
	*out = *in
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBStreamingStatus.
func (in *WBStreamingStatus) DeepCopy() *WBStreamingStatus {
	if in == nil {
		return nil
	}
	out := new(WBStreamingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiases) DeepCopyInto(out *WeightsAndBiases) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiases.
func (in *WeightsAndBiases) DeepCopy() *WeightsAndBiases {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiases)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WeightsAndBiases) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiasesList) DeepCopyInto(out *WeightsAndBiasesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WeightsAndBiases, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiasesList.
func (in *WeightsAndBiasesList) DeepCopy() *WeightsAndBiasesList {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiasesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WeightsAndBiasesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiasesSpec) DeepCopyInto(out *WeightsAndBiasesSpec) {
	*out = *in
	in.Infra.DeepCopyInto(&out.Infra)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiasesSpec.
func (in *WeightsAndBiasesSpec) DeepCopy() *WeightsAndBiasesSpec {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiasesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiasesStatus) DeepCopyInto(out *WeightsAndBiasesStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiasesStatus.
func (in *WeightsAndBiasesStatus) DeepCopy() *WeightsAndBiasesStatus {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiasesStatus)
	in.DeepCopyInto(out)
	return out
}
