//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Application) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationList) DeepCopyInto(out *ApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Application, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationList.
func (in *ApplicationList) DeepCopy() *ApplicationList {
	if in == nil {
		return nil
	}
	out := new(ApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSpec) DeepCopyInto(out *ApplicationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSpec.
func (in *ApplicationSpec) DeepCopy() *ApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatus) DeepCopyInto(out *ApplicationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatus.
func (in *ApplicationStatus) DeepCopy() *ApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBBackupFilesystemSpec) DeepCopyInto(out *WBBackupFilesystemSpec) {
	*out = *in
	out.StorageSize = in.StorageSize.DeepCopy()
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBBackupFilesystemSpec.
func (in *WBBackupFilesystemSpec) DeepCopy() *WBBackupFilesystemSpec {
	if in == nil {
		return nil
	}
	out := new(WBBackupFilesystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBBackupS3Spec) DeepCopyInto(out *WBBackupS3Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBBackupS3Spec.
func (in *WBBackupS3Spec) DeepCopy() *WBBackupS3Spec {
	if in == nil {
		return nil
	}
	out := new(WBBackupS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBBackupSpec) DeepCopyInto(out *WBBackupSpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(WBBackupS3Spec)
		**out = **in
	}
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(WBBackupFilesystemSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBBackupSpec.
func (in *WBBackupSpec) DeepCopy() *WBBackupSpec {
	if in == nil {
		return nil
	}
	out := new(WBBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBBackupStatus) DeepCopyInto(out *WBBackupStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBBackupStatus.
func (in *WBBackupStatus) DeepCopy() *WBBackupStatus {
	if in == nil {
		return nil
	}
	out := new(WBBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBClickHouseBackupSpec) DeepCopyInto(out *WBClickHouseBackupSpec) {
	*out = *in
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(WBBackupFilesystemSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBClickHouseBackupSpec.
func (in *WBClickHouseBackupSpec) DeepCopy() *WBClickHouseBackupSpec {
	if in == nil {
		return nil
	}
	out := new(WBClickHouseBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBClickHouseSpec) DeepCopyInto(out *WBClickHouseSpec) {
	*out = *in
	in.Backup.DeepCopyInto(&out.Backup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBClickHouseSpec.
func (in *WBClickHouseSpec) DeepCopy() *WBClickHouseSpec {
	if in == nil {
		return nil
	}
	out := new(WBClickHouseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBClickHouseStatus) DeepCopyInto(out *WBClickHouseStatus) {
	*out = *in
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = make([]WBStatusDetail, len(*in))
		copy(*out, *in)
	}
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
	in.BackupStatus.DeepCopyInto(&out.BackupStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBClickHouseStatus.
func (in *WBClickHouseStatus) DeepCopy() *WBClickHouseStatus {
	if in == nil {
		return nil
	}
	out := new(WBClickHouseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBDatabaseSpec) DeepCopyInto(out *WBDatabaseSpec) {
	*out = *in
	in.Backup.DeepCopyInto(&out.Backup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBDatabaseSpec.
func (in *WBDatabaseSpec) DeepCopy() *WBDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(WBDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBDatabaseStatus) DeepCopyInto(out *WBDatabaseStatus) {
	*out = *in
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = make([]WBStatusDetail, len(*in))
		copy(*out, *in)
	}
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
	in.BackupStatus.DeepCopyInto(&out.BackupStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBDatabaseStatus.
func (in *WBDatabaseStatus) DeepCopy() *WBDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(WBDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBKafkaBackupSpec) DeepCopyInto(out *WBKafkaBackupSpec) {
	*out = *in
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(WBBackupFilesystemSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBKafkaBackupSpec.
func (in *WBKafkaBackupSpec) DeepCopy() *WBKafkaBackupSpec {
	if in == nil {
		return nil
	}
	out := new(WBKafkaBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBKafkaConnection) DeepCopyInto(out *WBKafkaConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBKafkaConnection.
func (in *WBKafkaConnection) DeepCopy() *WBKafkaConnection {
	if in == nil {
		return nil
	}
	out := new(WBKafkaConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBKafkaSpec) DeepCopyInto(out *WBKafkaSpec) {
	*out = *in
	in.Backup.DeepCopyInto(&out.Backup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBKafkaSpec.
func (in *WBKafkaSpec) DeepCopy() *WBKafkaSpec {
	if in == nil {
		return nil
	}
	out := new(WBKafkaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBKafkaStatus) DeepCopyInto(out *WBKafkaStatus) {
	*out = *in
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = make([]WBStatusDetail, len(*in))
		copy(*out, *in)
	}
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
	out.Connection = in.Connection
	in.BackupStatus.DeepCopyInto(&out.BackupStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBKafkaStatus.
func (in *WBKafkaStatus) DeepCopy() *WBKafkaStatus {
	if in == nil {
		return nil
	}
	out := new(WBKafkaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBObjStorageBackupSpec) DeepCopyInto(out *WBObjStorageBackupSpec) {
	*out = *in
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(WBBackupFilesystemSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBObjStorageBackupSpec.
func (in *WBObjStorageBackupSpec) DeepCopy() *WBObjStorageBackupSpec {
	if in == nil {
		return nil
	}
	out := new(WBObjStorageBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBObjStorageSpec) DeepCopyInto(out *WBObjStorageSpec) {
	*out = *in
	in.Backup.DeepCopyInto(&out.Backup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBObjStorageSpec.
func (in *WBObjStorageSpec) DeepCopy() *WBObjStorageSpec {
	if in == nil {
		return nil
	}
	out := new(WBObjStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBObjStorageStatus) DeepCopyInto(out *WBObjStorageStatus) {
	*out = *in
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = make([]WBStatusDetail, len(*in))
		copy(*out, *in)
	}
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
	in.BackupStatus.DeepCopyInto(&out.BackupStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBObjStorageStatus.
func (in *WBObjStorageStatus) DeepCopy() *WBObjStorageStatus {
	if in == nil {
		return nil
	}
	out := new(WBObjStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisConfig) DeepCopyInto(out *WBRedisConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisConfig.
func (in *WBRedisConfig) DeepCopy() *WBRedisConfig {
	if in == nil {
		return nil
	}
	out := new(WBRedisConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisConnection) DeepCopyInto(out *WBRedisConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisConnection.
func (in *WBRedisConnection) DeepCopy() *WBRedisConnection {
	if in == nil {
		return nil
	}
	out := new(WBRedisConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisSentinelConfig) DeepCopyInto(out *WBRedisSentinelConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisSentinelConfig.
func (in *WBRedisSentinelConfig) DeepCopy() *WBRedisSentinelConfig {
	if in == nil {
		return nil
	}
	out := new(WBRedisSentinelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisSentinelSpec) DeepCopyInto(out *WBRedisSentinelSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(WBRedisSentinelConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisSentinelSpec.
func (in *WBRedisSentinelSpec) DeepCopy() *WBRedisSentinelSpec {
	if in == nil {
		return nil
	}
	out := new(WBRedisSentinelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisSpec) DeepCopyInto(out *WBRedisSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(WBRedisConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Sentinel != nil {
		in, out := &in.Sentinel, &out.Sentinel
		*out = new(WBRedisSentinelSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisSpec.
func (in *WBRedisSpec) DeepCopy() *WBRedisSpec {
	if in == nil {
		return nil
	}
	out := new(WBRedisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBRedisStatus) DeepCopyInto(out *WBRedisStatus) {
	*out = *in
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = make([]WBStatusDetail, len(*in))
		copy(*out, *in)
	}
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
	out.Connection = in.Connection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBRedisStatus.
func (in *WBRedisStatus) DeepCopy() *WBRedisStatus {
	if in == nil {
		return nil
	}
	out := new(WBRedisStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBStatusDetail) DeepCopyInto(out *WBStatusDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBStatusDetail.
func (in *WBStatusDetail) DeepCopy() *WBStatusDetail {
	if in == nil {
		return nil
	}
	out := new(WBStatusDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiases) DeepCopyInto(out *WeightsAndBiases) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiases.
func (in *WeightsAndBiases) DeepCopy() *WeightsAndBiases {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiases)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WeightsAndBiases) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiasesList) DeepCopyInto(out *WeightsAndBiasesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WeightsAndBiases, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiasesList.
func (in *WeightsAndBiasesList) DeepCopy() *WeightsAndBiasesList {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiasesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WeightsAndBiasesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiasesSpec) DeepCopyInto(out *WeightsAndBiasesSpec) {
	*out = *in
	in.Database.DeepCopyInto(&out.Database)
	in.Redis.DeepCopyInto(&out.Redis)
	in.Kafka.DeepCopyInto(&out.Kafka)
	in.ObjStorage.DeepCopyInto(&out.ObjStorage)
	in.ClickHouse.DeepCopyInto(&out.ClickHouse)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiasesSpec.
func (in *WeightsAndBiasesSpec) DeepCopy() *WeightsAndBiasesSpec {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiasesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightsAndBiasesStatus) DeepCopyInto(out *WeightsAndBiasesStatus) {
	*out = *in
	in.DatabaseStatus.DeepCopyInto(&out.DatabaseStatus)
	in.RedisStatus.DeepCopyInto(&out.RedisStatus)
	in.KafkaStatus.DeepCopyInto(&out.KafkaStatus)
	in.ObjStorageStatus.DeepCopyInto(&out.ObjStorageStatus)
	in.ClickHouseStatus.DeepCopyInto(&out.ClickHouseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightsAndBiasesStatus.
func (in *WeightsAndBiasesStatus) DeepCopy() *WeightsAndBiasesStatus {
	if in == nil {
		return nil
	}
	out := new(WeightsAndBiasesStatus)
	in.DeepCopyInto(out)
	return out
}
