{{- /* do not update crds here, please update in /victoria-metrics-operator/crd.yaml */ -}}
{{- /* this is used to add "helm.sh/resource-policy: keep" annotation for each crd */ -}}
{{- /* see this pull request https://github.com/VictoriaMetrics/helm-charts/pull/771 for details */ -}}
{{- $crdFiles := list }}
{{- if (dig "redis-operator" "enabled" false .Values.AsMap) }}
  {{- $crdFiles = append $crdFiles (.Files.Glob "external-crds/redis/**.yaml") }}
{{- end }}
{{- if (dig "strimzi-kafka-operator" "enabled" false .Values.AsMap) }}
  {{- $crdFiles = append $crdFiles (.Files.Glob "external-crds/kafka/**.yaml") }}
{{- end }}

{{- range $dir := $crdFiles }}
  {{- range $path, $_ := $dir}}
    {{- $crds := $.Files.Get $path | splitList "---" }}
    {{- $extra := dict "metadata" (dict "annotations" (dict "helm.sh/resource-policy" "keep")) }}
    {{- range $crds }}
      {{- $crd := merge (fromYaml .) $extra }}
      {{- range $attrKey, $attrValue := $crd }}
        {{- $attrKey }}: {{ toJson $attrValue }}
        {{- printf "\n" -}}
      {{ end }}
      {{- print "\n---\n" }}
    {{- end }}
  {{- end }}
{{- end }}
