{{- if (dig "moco" "enabled" true .Values.AsMap) }}
# Moco blockOwnerDeletion on PVCs requires statefulset-controller to update mysqlclusters/finalizers on OpenShift
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-moco-finalizers
rules:
  - apiGroups:
      - moco.cybozu.com
    resources:
      - mysqlclusters/finalizers
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-moco-finalizers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-moco-finalizers
subjects:
  - kind: ServiceAccount
    name: statefulset-controller
    namespace: kube-system
{{- end }}
