{{- if and .Values.telemetry.enabled (eq .Values.telemetry.mode "managed") }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: {{ include "operator.telemetry.vmsingleName" . }}
  namespace: {{ include "operator.telemetry.namespace" . }}
  labels:
    app.kubernetes.io/component: telemetry
    app.kubernetes.io/part-of: wandb
spec:
  retentionPeriod: {{ .Values.telemetry.managed.retentionPeriod | quote }}
  {{- with .Values.telemetry.managed.vmsingle.extraArgs }}
  extraArgs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: {{ include "operator.telemetry.vmagentName" . }}
  namespace: {{ include "operator.telemetry.namespace" . }}
  labels:
    app.kubernetes.io/component: telemetry
    app.kubernetes.io/part-of: wandb
spec:
  selectAllByDefault: {{ .Values.telemetry.managed.vmagent.selectAllByDefault }}
  remoteWrite:
    - url: {{ printf "http://vmsingle-%s:8428/api/v1/write" (include "operator.telemetry.vmsingleName" .) | quote }}
---
apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: {{ include "operator.telemetry.vlsingleName" . }}
  namespace: {{ include "operator.telemetry.namespace" . }}
  labels:
    app.kubernetes.io/component: telemetry
    app.kubernetes.io/part-of: wandb
spec:
  retentionPeriod: {{ .Values.telemetry.managed.retentionPeriod | quote }}
---
apiVersion: operator.victoriametrics.com/v1
kind: VTSingle
metadata:
  name: {{ include "operator.telemetry.vtsingleName" . }}
  namespace: {{ include "operator.telemetry.namespace" . }}
  labels:
    app.kubernetes.io/component: telemetry
    app.kubernetes.io/part-of: wandb
spec:
  retentionPeriod: {{ .Values.telemetry.managed.retentionPeriod | quote }}
{{- end }}
