name: "OperatorHub Release Workflow"
on:
  workflow_dispatch:
  push:
    branches:
      - feature/olm-operator-release
# on:
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'operator/olm/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract version from version.txt file
        id: extract_version
        run: |
          if [[ ! -f version.txt ]]; then
            echo "version.txt file not found!"
            exit 1
          fi
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Operator Image
        run: |
          docker build -t quay.io/wandb_tools/wandb-k8s-operator:${{ env.VERSION }} .

      # - name: Push Operator Image
      #   run: |
      #     docker push quay.io/wandb_tools/wandb-k8s-operator:${{ env.VERSION }}

      # Update the CSV for the new version
      - name: Update CSV
        run: |
          echo "Updating CSV for version ${{ env.VERSION }}"
          sed -i "s/1.0.0/${{ env.VERSION }}/g" olm/olm-catalog/manifests/wandb-operator.clusterserviceversion.yaml

      # Build & Publish the Bundle
      - name: Build and Publish Bundle
        run: |
          docker build -t quay.io/wandb_tools/wandb-operator:v${{ env.VERSION }} -f olm/olm-catalog/bundle.Dockerfile olm/olm-catalog/
          # docker push quay.io/wandb_tools/wandb-operator:v${{ env.VERSION }}

      # - name: Update OPM Index
      #   run: |
      #     opm index add --container-tool=docker --bundles=quay.io/wandb_tools/wandb-operator:v1.0.0,quay.io/wandb_tools/wandb-operator:v${{ env.VERSION }} --tag  quay.io/wandb_tools/wandb-operator-index:v${{ env.VERSION }}

      # Checkout Community Operators Repository
      - name: Checkout Community Operators Repository
        uses: actions/checkout@v3
        with:
          repository: k8s-operatorhub/community-operators
          path: community-operators

      # Create a new versioned directory and copy files
      - name: Create versioned directory and copy files
        run: |
          VERSION_DIR="community-operators/operators/wandb-operator/${{ env.VERSION }}"
          mkdir -p $VERSION_DIR
          cp -r olm/olm-catalog/* $VERSION_DIR/
          rm -rf community-operators/operators/wandb-operator/${{ env.VERSION }}/ci.yaml
          cat community-operators/operators/wandb-operator/${{ env.VERSION }}/manifests/wandb-operator.clusterserviceversion.yaml

      # - name: Set up GitHub CLI
      #   uses: cli/cli-action@v2

      # - name: Commit changes and create a Pull Request
      #   run: |
      #     cd community-operators
      #     git add .
      #     git commit -m "Add release $VERSION for wandb-operator"
      #     git push origin add-$VERSION --force
      #     gh pr create --title "Add $VERSION for wandb-operator" --body "This PR adds the $VERSION release of wandb-operator." --base main --head add-$VERSION
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
