name: "OperatorHub Release Workflow"
on:
  push:
    branches:
      - feature/olm-operator-release

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract version from version.txt file
        id: extract_version
        run: |
          if [[ ! -f version.txt ]]; then
            echo "version.txt file not found!"
            exit 1
          fi
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Operator Image
        run: |
          docker build -t quay.io/wandb_tools/wandb-k8s-operator:${{ env.VERSION }} .

      # - name: Push Operator Image
      #   run: |
      #     docker push quay.io/wandb_tools/wandb-k8s-operator:${{ env.VERSION }}

      # Update the CSV for the new version
      - name: Update CSV
        run: |
          echo "Updating CSV for version ${{ env.VERSION }}"
          sed -i "s/1.0.0/${{ env.VERSION }}/g" olm/olm-catalog/manifests/wandb-operator.clusterserviceversion.yaml

      # Build & Publish the Bundle
      - name: Build and Publish Bundle
        run: |
          docker build -t quay.io/wandb_tools/wandb-operator:v${{ env.VERSION }} -f olm/olm-catalog/bundle.Dockerfile olm/olm-catalog/
          # docker push quay.io/wandb_tools/wandb-operator:v${{ env.VERSION }}

      - name: Checkout the forked repository
        uses: actions/checkout@v3
        with:
          repository: amanpruthi/community-operators 
          path: community-operators 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new branch for version ${{ env.VERSION }}
        run: |
          git checkout -b add-${{ env.VERSION }}

      - name: Create versioned directory and copy files
        run: |
          VERSION_DIR="community-operators/operators/wandb-operator/${{ env.VERSION }}"
          mkdir -p $VERSION_DIR
          cp -r olm/olm-catalog/* $VERSION_DIR/
          rm -rf community-operators/operators/wandb-operator/${{ env.VERSION }}/ci.yaml

      - name: Stage, commit, and push changes
        run: |
          git add .
          git commit -m "Add release ${{ env.VERSION }} for wandb-operator" --no-gpg-sign
          git push origin add-${{ env.VERSION }}

      - name: Create a pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          source_branch: add-${{ env.VERSION }}
          pr_title: "Add ${{ env.VERSION }} for wandb-operator"
          pr_body: "This PR adds the ${{ env.VERSION }} release of wandb-operator."
          github_token: ${{ secrets.GITHUB_TOKEN }}

