name: "Run Tests"
on:
  push:
    branches:
      - v2
      - main
  pull_request:
    branches:
      - v2
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.26.3
      - name: Install dependencies
        run: go mod download
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.28.1
      - name: Install Helm
        uses: azure/setup-helm@bf6a7d304bc2fdb57e0331155b7ebf2c504acf0a # v4
        with:
          version: v3.19.0
      - name: Resolve chart dependencies
        run: |
          helm repo add wandb https://charts.wandb.ai/
          helm repo add moco https://cybozu-go.github.io/moco/
          helm repo add ot-container-kit https://ot-container-kit.github.io/helm-charts
          helm repo add seaweedfs https://seaweedfs.github.io/seaweedfs-operator/
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add altinity https://helm.altinity.com
          helm repo add victoria-metrics https://victoriametrics.github.io/helm-charts/
          helm repo add grafana https://grafana.github.io/helm-charts
          helm dependency build deploy/operator
          git diff --exit-code deploy/operator/Chart.lock
      - name: Tests
        run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.26.3
      - name: Build
        run: make build

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.26.3
      - name: Install dependencies
        run: go mod download
      - name: Check for changes in go.mod or go.sum
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
